apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-blog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-blog
  template:
    metadata:
      labels:
        app: my-blog
    spec:
      containers:
      - name: my-blog-container
        image: ghcr.io/tiwariparth/blogops:latest
        ports:
        - containerPort: 80